name: npo_automative_app
description: НПО Автоматив - автоматизация производства.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  uuid: ^3.0.6
  flutter_bloc: ^8.1.1
  formz: ^0.4.1
  json_serializable: ^6.3.1
  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
